module.exports = Object.freeze({
    SIGNUP_SUCCESS_MSG: 'Successfully Signup',
    ERR_MSG: 'Internal server error',
    ROUND: 10,
    GET_MSG: 'Found record',
    SIGNUP_SUB: 'Successfully Created!',
    SIGNUP_TEXT: 'Congratulations you have signed up, we will get back to you soon!',
    SUPER_ADMIN_SUCCESS: 'Super admin created',
    LOGIN_EMAIL_NOT_FOUND: 'Email does not exist',
    LOGIN_PASSWORD_ERR: 'Wrong password',
    LOGIN_SUCCESS_MSG: 'Login Successfully!',
    INVALID_TOKEN: 'Invalid Token',
    CONTACT_US_SUBJECT: 'Thanks for contacting us',
    CONTACT_US_SUCCESS_MSG: 'Thanks for contacting us. We will be in touch with you shortly!',
    USER_NOT_FOUND: 'User not found',
    USER_TRUNCATE_SUCCESS: 'Data have been truncated successfully',
    USER_FOUND_SUCCESS: 'Found record',
    SUCCESSFULLY_UPDATED: 'Successfully updated',
    DETAILS_FOUND: 'Details found successfully',
    SUCCESSFULLY_DELETED: 'Successfully  deleted',
    SUCCESSFULLY_ADDED: 'Successfully added',
    CONFIRMPASSWORD_NOT_MATCH: 'Confirm password not match',
    UPDATE_PASSWORD: 'Password changed successfully',
    INVALID_ID: 'Invalid id',
    FORGETPASSWORD_LINK: 'Forget password link',
    EMAIL_SEND: 'Email send successfully',
    EMAIL_SUBJECT: 'Your account has been created',
    EMAIL_REJECTION: 'Your complaint has been rejected',
    INVALID_TOKEN: 'Token not found',
    USER_VERIFY: 'User verify',
    NOT_VERIFY: 'User not verify',
    NOT_ACCESS: 'Sorry, you do not have access',
    COMPLAINT_ACCEPTED: 'Email for complaint approved',
    COMPLAINT_REJECTED: 'Email for complaint rejected'
})
